server:
  port: 7777

spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${cn.datasource.driver-class-name}
      url: jdbc:mysql://${cn.datasource.host}:${cn.datasource.port}/${cn.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${cn.datasource.username}
      password: ${cn.datasource.password}

cn:
  ljz:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token